name: simple-apps

services:
  web:
    image: nginx
    ports:
      - "8000:80"

  web-httpd:
    image: httpd
    ports:
      - "8001:80"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    enviroment:
    PGADMIN_DEFAULT_EMAIL: admin123@gmail.com
    PGADMIN_DEFAULT_PASSWORD: admin123
