name: simple-apps

services:
  web:doc
    image: nginx
    ports:
      - "8000:80"

  web-httpd:
    image: httpd
    ports:
      - "8001:80"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"
